import { Vendor } from "../types/vendors";

/**
 * Real Arizona Vendors from Surprise Granite Pro Network
 * Source: https://www.surprisegranite.com/company/vendors-list
 */

export const ARIZONA_VENDORS: Vendor[] = [
  // SURPRISE GRANITE - Main Fabricator
  {
    id: "sg-main",
    name: "Surprise Granite",
    type: "fabricator",
    description: "Premier granite fabrication and countertop installation. Your trusted partner for custom countertops, remnants, and full slabs. Family-owned with expert craftsmanship serving Arizona since 2010.",
    location: {
      address: "11560 N. Dysart Rd.",
      city: "Surprise",
      state: "AZ",
      zipCode: "85379",
      coordinates: { latitude: 33.6848, longitude: -112.3621 },
    },
    contact: {
      phone: "(602) 833-3189",
      email: "info@surprisegranite.com",
      website: "www.surprisegranite.com",
    },
    businessHours: {
      monday: "8:00 AM - 5:00 PM",
      tuesday: "8:00 AM - 5:00 PM",
      wednesday: "8:00 AM - 5:00 PM",
      thursday: "8:00 AM - 5:00 PM",
      friday: "8:00 AM - 5:00 PM",
      saturday: "9:00 AM - 3:00 PM",
    },
    images: ["https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800"],
    rating: 4.9,
    reviewCount: 342,
    verified: true,
    samplesAvailable: true,
    specialties: ["Granite Fabrication", "Custom Countertops", "Remnants", "Full Slabs", "Installation"],
    inventory: { granite: 150, marble: 80, quartzite: 45, quartz: 120 },
    tags: ["fabricator", "installation", "custom work", "remnants"],
    supplierRelationships: [
      {
        vendorId: "msi-phoenix",
        vendorName: "MSI Surfaces",
        relationshipType: "primary-supplier",
        activeInventory: ["Calacatta Classique", "Alaska White Granite", "Super White Quartzite"],
      },
      {
        vendorId: "cosentino-tempe",
        vendorName: "Cosentino",
        relationshipType: "primary-supplier",
        activeInventory: ["Silestone White Storm", "Dekton Aura", "Sensa Orinoco"],
      },
      {
        vendorId: "the-yard-az",
        vendorName: "The Yard AZ",
        relationshipType: "secondary-supplier",
        activeInventory: ["Black Galaxy", "Colonial White", "Carrara White", "Taj Mahal"],
      },
    ],
  },

  // COUNTERTOP SURFACES
  {
    id: "msi-phoenix",
    name: "MSI Surfaces - Phoenix",
    type: "stone-supplier",
    description: "Extensive range of quartz, granite, and porcelain surfaces with a state-of-the-art showroom. Exclusive discounted pricing through Surprise Granite's Pro Network.",
    location: {
      address: "4405 W Roosevelt St",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85043",
      coordinates: { latitude: 33.4484, longitude: -112.1563 },
    },
    contact: {
      phone: "(602) 393-6330",
      email: "phoenix@msisurfaces.com",
      website: "www.msisurfaces.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800"],
    rating: 5.0,
    reviewCount: 428,
    verified: true,
    samplesAvailable: true,
    specialties: ["Natural Stone", "Quartz", "Porcelain", "Wholesale", "Pro Network Partner"],
    inventory: { granite: 500, marble: 350, quartzite: 200, quartz: 800 },
  },

  {
    id: "cosentino-tempe",
    name: "Cosentino - Tempe",
    type: "stone-supplier",
    description: "Global leader in innovative surfaces like Silestone quartz and Dekton ultra-compact surfaces. Premium quality for residential and commercial projects.",
    location: {
      address: "8307 S Priest Dr",
      city: "Tempe",
      state: "AZ",
      zipCode: "85284",
      coordinates: { latitude: 33.3426, longitude: -111.9705 },
    },
    contact: {
      phone: "(480) 763-9400",
      email: "tempe@cosentino.com",
      website: "www.cosentino.com",
    },
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800"],
    rating: 4.8,
    reviewCount: 521,
    verified: true,
    samplesAvailable: true,
    specialties: ["Silestone", "Dekton", "Sensa Granite", "Premium Surfaces"],
    inventory: { granite: 200, marble: 150, quartzite: 100, quartz: 1000 },
  },

  {
    id: "arizona-tile-tempe",
    name: "Arizona Tile - Tempe",
    type: "tile-store",
    description: "Family-owned since 1977, offering over 230 varieties of granite, marble, quartz, and more. Tempe Showroom & Slab Warehouse.",
    location: {
      address: "8829 S Priest Dr",
      city: "Tempe",
      state: "AZ",
      zipCode: "85284",
      coordinates: { latitude: 33.3358, longitude: -111.9706 },
    },
    contact: {
      phone: "(480) 893-9393",
      email: "tempe@arizonatile.com",
      website: "www.arizonatile.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800"],
    rating: 4.6,
    reviewCount: 387,
    verified: true,
    samplesAvailable: true,
    specialties: ["Natural Stone", "Tile", "Pavers", "Hardscaping", "230+ Varieties"],
    inventory: { granite: 300, marble: 250, quartzite: 150, quartz: 400 },
  },

  {
    id: "aracruz-granite",
    name: "Aracruz Granite",
    type: "stone-supplier",
    description: "Offers a wide selection of natural stone slabs, including granite and quartzite. Set appointments using Surprise Granite as fabricator.",
    location: {
      address: "2310 W Sherman St",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85009",
      coordinates: { latitude: 33.4525, longitude: -112.0932 },
    },
    contact: {
      phone: "(602) 252-1171",
      email: "info@aracruzgranite.com",
      website: "www.aracruzgranite.com",
    },
    images: ["https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800"],
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    samplesAvailable: true,
    specialties: ["Granite Slabs", "Quartzite", "Natural Stone", "Wholesale"],
    inventory: { granite: 250, marble: 120, quartzite: 180, quartz: 80 },
  },

  {
    id: "architectural-surfaces",
    name: "Architectural Surfaces",
    type: "stone-supplier",
    description: "Leading importer of natural stone, quartz, and tile with 35 national showrooms. Scottsdale location serves Arizona market.",
    location: {
      address: "9175 E Pima Center Pkwy suite a-1",
      city: "Scottsdale",
      state: "AZ",
      zipCode: "85258",
      coordinates: { latitude: 33.6424, longitude: -111.8902 },
    },
    contact: {
      phone: "(480) 210-3570",
      email: "scottsdale@architecturalsurfaces.com",
      website: "www.architecturalsurfaces.com",
    },
    images: ["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800"],
    rating: 4.5,
    reviewCount: 298,
    verified: true,
    samplesAvailable: true,
    specialties: ["Imported Stone", "Quartz", "Tile", "35 National Showrooms"],
    inventory: { granite: 220, marble: 180, quartzite: 90, quartz: 350 },
  },

  {
    id: "bolder-image-stone",
    name: "Bolder Image Stone",
    type: "countertop-specialist",
    description: "Specializes in granite, marble, and quartz countertops with custom fabrication services.",
    location: {
      address: "4101 W Van Buren St STE#3",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85009",
      coordinates: { latitude: 33.4524, longitude: -112.1421 },
    },
    contact: {
      phone: "(602) 484-7700",
      email: "info@bolderimages tone.com",
      website: "www.bolderimagestone.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800"],
    rating: 4.8,
    reviewCount: 203,
    verified: true,
    samplesAvailable: true,
    specialties: ["Granite", "Marble", "Quartz", "Custom Fabrication"],
    inventory: { granite: 120, marble: 85, quartzite: 45, quartz: 150 },
  },

  {
    id: "cambria-avondale",
    name: "Cambria",
    type: "stone-supplier",
    description: "Premium quartz surfaces with exclusive designs, available by appointment only. American-made quartz countertops.",
    location: {
      address: "1250 N Fairway Dr Building C, Suite 103",
      city: "Avondale",
      state: "AZ",
      zipCode: "85323",
      coordinates: { latitude: 33.4439, longitude: -112.3497 },
    },
    contact: {
      phone: "(623) 471-6872",
      email: "avondale@cambriausa.com",
      website: "www.cambriausa.com",
    },
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800"],
    rating: 4.9,
    reviewCount: 412,
    verified: true,
    samplesAvailable: true,
    specialties: ["Premium Quartz", "Exclusive Designs", "American Made", "By Appointment"],
    inventory: { granite: 0, marble: 0, quartzite: 0, quartz: 600 },
  },

  {
    id: "classic-surfaces",
    name: "Classic Surfaces",
    type: "stone-supplier",
    description: "Provides high-quality surfacing materials, including quartz and natural stone. Phoenix warehouse location.",
    location: {
      address: "4645 W Mcdowell Rd Suite #101",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85035",
      coordinates: { latitude: 33.4659, longitude: -112.1652 },
    },
    contact: {
      phone: "(602) 334-1972",
      email: "info@classic-surfaces.com",
      website: "www.classic-surfaces.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800"],
    rating: 4.6,
    reviewCount: 187,
    verified: true,
    samplesAvailable: true,
    specialties: ["Quartz", "Natural Stone", "Surfacing Materials"],
    inventory: { granite: 140, marble: 95, quartzite: 60, quartz: 280 },
  },

  {
    id: "cactus-stone-tile",
    name: "Cactus Stone & Tile",
    type: "stone-supplier",
    description: "Wholesale distributor of ceramic and stone tile. Wholesale distributor of natural stone slabs. Natural Stone, Granite, Marble, Tile.",
    location: {
      address: "5005 E Madison St",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85034",
      coordinates: { latitude: 33.4655, longitude: -111.9818 },
    },
    contact: {
      phone: "(602) 914-2202",
      email: "info@cactusstone.com",
      website: "www.cactusstone.com",
    },
    images: ["https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800"],
    rating: 4.7,
    reviewCount: 256,
    verified: true,
    samplesAvailable: true,
    specialties: ["Wholesale Tile", "Natural Stone Slabs", "Granite", "Marble"],
    inventory: { granite: 180, marble: 120, quartzite: 70, quartz: 200 },
  },

  {
    id: "sun-stone",
    name: "Sun Stone",
    type: "stone-supplier",
    description: "Offers natural stone and quartz surfaces for countertops and outdoor applications.",
    location: {
      address: "2727 W Encanto Blvd",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85009",
      coordinates: { latitude: 33.4706, longitude: -112.1106 },
    },
    contact: {
      phone: "(602) 353-1618",
      email: "info@sunstoneus.com",
      website: "www.sunstoneus.com",
    },
    images: ["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800"],
    rating: 4.5,
    reviewCount: 142,
    verified: true,
    samplesAvailable: true,
    specialties: ["Natural Stone", "Quartz", "Outdoor Applications"],
    inventory: { granite: 160, marble: 90, quartzite: 75, quartz: 190 },
  },

  {
    id: "stone-collection-phoenix",
    name: "The Stone Collection - Phoenix",
    type: "stone-supplier",
    description: "Enriching Environments by offering premium Natural Stone and Quartz Slabs.",
    location: {
      address: "4747 E Cotton Center Blvd",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85040",
      coordinates: { latitude: 33.4108, longitude: -111.9834 },
    },
    contact: {
      phone: "(602) 889-2067",
      email: "info@thestonecollection.com",
      website: "www.thestonecollection.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800"],
    rating: 4.7,
    reviewCount: 224,
    verified: true,
    samplesAvailable: true,
    specialties: ["Premium Natural Stone", "Quartz Slabs", "High-End Selection"],
    inventory: { granite: 195, marble: 165, quartzite: 110, quartz: 305 },
  },

  // TILE VENDORS
  {
    id: "unique-design-solutions",
    name: "Unique Design Solutions",
    type: "tile-store",
    description: "Discover Premium Tile Solutions! Specializes in high-quality ceramic, porcelain, and glass tiles for kitchens, bathrooms, and outdoor spaces. Exclusive discounted pricing through Surprise Granite's Pro Network.",
    location: {
      address: "2514 E Mohawk Ln # 101",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85050",
      coordinates: { latitude: 33.5706, longitude: -112.0336 },
    },
    contact: {
      phone: "(602) 971-3166",
      email: "info@uniquedesignsolutions.com",
      website: "www.uniquedesignsolutions.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800"],
    rating: 5.0,
    reviewCount: 186,
    verified: true,
    samplesAvailable: true,
    specialties: ["Ceramic Tile", "Porcelain Tile", "Glass Tile", "Custom Designs", "Pro Network Partner"],
  },

  {
    id: "emser-tile",
    name: "Emser Tile",
    type: "tile-store",
    description: "Leading designer of ceramic, porcelain, and natural stone tiles for residential and commercial projects.",
    location: {
      address: "2604 S 38th St",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85034",
      coordinates: { latitude: 33.4278, longitude: -111.9965 },
    },
    contact: {
      phone: "(602) 263-8453",
      email: "phoenix@emser.com",
      website: "www.emser.com",
    },
    images: ["https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800"],
    rating: 4.6,
    reviewCount: 342,
    verified: true,
    samplesAvailable: true,
    specialties: ["Ceramic Tile", "Porcelain Tile", "Natural Stone", "Commercial Projects"],
  },

  {
    id: "facings-america",
    name: "Facings of America",
    type: "tile-store",
    description: "Over 60 years of expertise in tile, stone, and decorative surfaces for interior and exterior applications.",
    location: {
      address: "15455 N Greenway Hayden Loop",
      city: "Scottsdale",
      state: "AZ",
      zipCode: "85260",
      coordinates: { latitude: 33.6216, longitude: -111.9081 },
    },
    contact: {
      phone: "(480) 948-5045",
      email: "info@facingsofamerica.com",
      website: "www.facingsofamerica.com",
    },
    images: ["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800"],
    rating: 4.7,
    reviewCount: 267,
    verified: true,
    samplesAvailable: true,
    specialties: ["Tile", "Stone", "Decorative Surfaces", "60+ Years Experience"],
  },

  {
    id: "mexi-tile",
    name: "Mexi-Tile Stone Expo",
    type: "tile-store",
    description: "Direct importer of natural stone, pavers, and hand-crafted tiles since 1977.",
    location: {
      address: "2036 W. Greenway Rd",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85023",
      coordinates: { latitude: 33.6229, longitude: -112.0879 },
    },
    contact: {
      phone: "(623) 234-4020",
      email: "info@mexitile.com",
      website: "www.mexitile.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800"],
    rating: 4.5,
    reviewCount: 178,
    verified: true,
    samplesAvailable: true,
    specialties: ["Natural Stone", "Pavers", "Hand-Crafted Tiles", "Direct Import"],
  },

  {
    id: "monterrey-tile",
    name: "Monterrey Tile",
    type: "tile-store",
    description: "Specializes in ceramic, porcelain, and natural stone tiles.",
    location: {
      address: "3232 S. 48TH ST. Suite 111",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85040",
      coordinates: { latitude: 33.4134, longitude: -111.9791 },
    },
    contact: {
      phone: "(480) 219-2494",
      email: "info@monterreytile.com",
      website: "www.monterreytile.com",
    },
    images: ["https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800"],
    rating: 4.4,
    reviewCount: 134,
    verified: true,
    samplesAvailable: true,
    specialties: ["Ceramic Tile", "Porcelain Tile", "Natural Stone"],
  },

  {
    id: "qdi-surfaces",
    name: "QDI Surfaces",
    type: "tile-store",
    description: "Offers natural stone, porcelain, glass, and ceramic tiles for floors, walls, and backsplashes.",
    location: {
      address: "2633 N 24th Dr",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85009",
      coordinates: { latitude: 33.4762, longitude: -112.1043 },
    },
    contact: {
      phone: "(602) 269-7900",
      email: "info@qdisurfaces.com",
      website: "www.qdisurfaces.com",
    },
    images: ["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800"],
    rating: 4.6,
    reviewCount: 198,
    verified: true,
    samplesAvailable: true,
    specialties: ["Natural Stone", "Porcelain", "Glass Tile", "Ceramic Tile"],
  },

  {
    id: "villagio-tile",
    name: "Villagio Tile & Stone",
    type: "tile-store",
    description: "Premier tile and stone showroom offering natural stone and porcelain tiles with custom design services.",
    location: {
      address: "8340 E Raintree Dr",
      city: "Scottsdale",
      state: "AZ",
      zipCode: "85260",
      coordinates: { latitude: 33.6153, longitude: -111.8911 },
    },
    contact: {
      phone: "(480) 422-6700",
      email: "info@villagiotile.com",
      website: "www.villagiotile.com",
    },
    images: ["https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800"],
    rating: 4.8,
    reviewCount: 289,
    verified: true,
    samplesAvailable: true,
    specialties: ["Natural Stone", "Porcelain Tiles", "Custom Design", "Premier Showroom"],
  },

  // THE YARD AZ - Stone Slabs & Remnants Specialist
  {
    id: "the-yard-az",
    name: "The Yard AZ",
    type: "stone-supplier",
    description: "Arizona's premier destination for stone slabs and remnants. Huge selection of granite, marble, quartzite, and quartz at competitive prices. Perfect for DIY homeowners and professional contractors. Specializing in remnants and full slabs.",
    location: {
      address: "2334 W Lone Cactus Dr",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85027",
      coordinates: { latitude: 33.6912, longitude: -112.1054 },
    },
    contact: {
      phone: "(602) 633-9273",
      email: "info@theyardaz.com",
      website: "www.theyardaz.com",
    },
    businessHours: {
      monday: "8:00 AM - 5:00 PM",
      tuesday: "8:00 AM - 5:00 PM",
      wednesday: "8:00 AM - 5:00 PM",
      thursday: "8:00 AM - 5:00 PM",
      friday: "8:00 AM - 5:00 PM",
      saturday: "9:00 AM - 2:00 PM",
    },
    images: ["https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800"],
    rating: 4.7,
    reviewCount: 215,
    verified: true,
    samplesAvailable: true,
    specialties: ["Remnants", "Full Slabs", "Granite", "Marble", "Quartzite", "Quartz", "Discount Pricing"],
    inventory: { granite: 300, marble: 180, quartzite: 120, quartz: 250 },
    tags: ["remnants", "slabs", "discount", "DIY friendly", "contractor pricing"],
    stoneInventory: [
      {
        id: "yard-granite-001",
        stoneName: "Black Galaxy",
        stoneType: "Granite",
        color: "Black",
        finish: "Polished",
        pricePerSqFt: 45,
        availability: "In Stock",
        images: ["https://images.unsplash.com/photo-1594737626072-90dc274bc2bd?w=600"],
      },
      {
        id: "yard-granite-002",
        stoneName: "Colonial White",
        stoneType: "Granite",
        color: "White",
        finish: "Polished",
        pricePerSqFt: 38,
        availability: "In Stock",
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600"],
      },
      {
        id: "yard-marble-001",
        stoneName: "Carrara White",
        stoneType: "Marble",
        color: "White",
        finish: "Polished",
        pricePerSqFt: 55,
        availability: "In Stock",
        images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=600"],
      },
      {
        id: "yard-quartz-001",
        stoneName: "Calacatta Laza",
        stoneType: "Quartz",
        color: "White",
        finish: "Polished",
        supplierBrand: "Caesarstone",
        pricePerSqFt: 62,
        availability: "In Stock",
        images: ["https://images.unsplash.com/photo-1615875605825-5c7a2fbf8c6e?w=600"],
      },
      {
        id: "yard-quartzite-001",
        stoneName: "Taj Mahal",
        stoneType: "Quartzite",
        color: "White",
        finish: "Polished",
        pricePerSqFt: 78,
        availability: "In Stock",
        images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600"],
      },
    ],
  },
];

